opt_in_rules:
#  - empty_count
  - force_unwrapping

disabled_rules:
  - line_length
  - todo
  - cyclomatic_complexity
  - function_body_length

excluded:
  - Pods

statement_position:
  statement_mode: uncuddled_else